name: Generate functions
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}, {2}.', 'Hi', 'world', 'I am Shio' )}}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ')}}