name: Manual
on: 
  workflow_dispatch: 
    inputs:
      shio-action:
        type: choice
        options:
          - info
          - warn
          - error

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.shio-action }}"